package org.esprit.finovate.services;

import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.properties.HorizontalAlignment;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import com.itextpdf.layout.properties.VerticalAlignment;
import org.esprit.finovate.entities.User;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

public class PDFExportService {

    private static final DeviceRgb PRIMARY_COLOR = new DeviceRgb(35, 127, 78); // Finovate green
    private static final DeviceRgb HEADER_BG_COLOR = new DeviceRgb(35, 127, 78);
    private static final DeviceRgb ROW_ALT_COLOR = new DeviceRgb(240, 253, 244);
    private static final DeviceRgb TEXT_COLOR = new DeviceRgb(33, 37, 41);
    private static final DeviceRgb LIGHT_GRAY = new DeviceRgb(108, 117, 125);

    public void exportUsersToPDF(List<User> users, String filePath) throws FileNotFoundException, IOException {
        PdfWriter writer = new PdfWriter(filePath);
        PdfDocument pdfDoc = new PdfDocument(writer);
        pdfDoc.setDefaultPageSize(PageSize.A4);

        try (Document document = new Document(pdfDoc)) {
            // Load fonts
            PdfFont regularFont = PdfFontFactory.createFont();
            PdfFont boldFont = PdfFontFactory.createFont();

            // Add header with logo and title
            addHeader(document, boldFont);

            // Add summary section
            addSummarySection(document, users, boldFont, regularFont);

            // Add users table
            addUsersTable(document, users, boldFont, regularFont);

            // Add footer
            addFooter(document, regularFont);
        }
    }

    private void addHeader(Document document, PdfFont boldFont) {
        // Create header table with logo and title
        Table headerTable = new Table(UnitValue.createPercentArray(new float[]{20, 80}));
        headerTable.setWidth(UnitValue.createPercentValue(100));
        headerTable.setBorder(Border.NO_BORDER);

        // Logo cell
        Cell logoCell = new Cell();
        logoCell.setBorder(Border.NO_BORDER);
        logoCell.setVerticalAlignment(VerticalAlignment.MIDDLE);

        try {
            InputStream logoStream = getClass().getResourceAsStream("/logo.png");
            if (logoStream != null) {
                byte[] logoBytes = logoStream.readAllBytes();
                Image logo = new Image(ImageDataFactory.create(logoBytes));
                logo.setHeight(50);
                logo.setWidth(50);
                logoCell.add(logo);
            }
        } catch (IOException e) {
            // If logo not found, add placeholder text
            logoCell.add(new Paragraph("FINOVATE").setFont(boldFont).setFontColor(PRIMARY_COLOR).setFontSize(20));
        }
        headerTable.addCell(logoCell);

        // Title cell
        Cell titleCell = new Cell();
        titleCell.setBorder(Border.NO_BORDER);
        titleCell.setVerticalAlignment(VerticalAlignment.MIDDLE);
        titleCell.setTextAlignment(TextAlignment.RIGHT);

        Paragraph title = new Paragraph("USERS LIST REPORT")
                .setFont(boldFont)
                .setFontSize(28)
                .setFontColor(PRIMARY_COLOR)
                .setMargin(0);
        titleCell.add(title);

        Paragraph subtitle = new Paragraph("Generated by Finovate System")
                .setFontColor(LIGHT_GRAY)
                .setFontSize(10)
                .setMargin(0);
        titleCell.add(subtitle);
        headerTable.addCell(titleCell);

        document.add(headerTable);
        document.add(new Paragraph().setMarginBottom(20));

        // Add decorative line
        document.add(new Paragraph("_______________________________" +
                "______________________________________________________________")
                .setFontColor(new DeviceRgb(222, 226, 230))
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(20));
    }

    private void addSummarySection(Document document, List<User> users, PdfFont boldFont, PdfFont regularFont) {
        // Summary cards
        Table summaryTable = new Table(UnitValue.createPercentArray(new float[]{25, 25, 25, 25}));
        summaryTable.setWidth(UnitValue.createPercentValue(100));
        summaryTable.setMarginBottom(20);

        // Count by role
        long adminCount = users.stream().filter(u -> "ADMIN".equalsIgnoreCase(u.getRole())).count();
        long userCount = users.stream().filter(u -> !"ADMIN".equalsIgnoreCase(u.getRole())).count();

        addSummaryCard(summaryTable, "Total Users", String.valueOf(users.size()), boldFont);
        addSummaryCard(summaryTable, "Administrators", String.valueOf(adminCount), boldFont);
        addSummaryCard(summaryTable, "Regular Users", String.valueOf(userCount), boldFont);
        addSummaryCard(summaryTable, "Generated Date", new SimpleDateFormat("dd/MM/yyyy").format(new Date()), boldFont);

        document.add(summaryTable);
        document.add(new Paragraph().setMarginBottom(15));
    }

    private void addSummaryCard(Table table, String label, String value, PdfFont boldFont) {
        Cell cell = new Cell();
        cell.setBackgroundColor(ROW_ALT_COLOR);
        cell.setBorder(new SolidBorder(PRIMARY_COLOR, 1));
        cell.setPadding(10);

        Paragraph labelPara = new Paragraph(label)
                .setFontColor(LIGHT_GRAY)
                .setFontSize(9)
                .setMargin(0);
        cell.add(labelPara);

        Paragraph valuePara = new Paragraph(value)
                .setFont(boldFont)
                .setFontColor(PRIMARY_COLOR)
                .setFontSize(18)
                .setMargin(0);
        cell.add(valuePara);

        table.addCell(cell);
    }

    private void addUsersTable(Document document, List<User> users, PdfFont boldFont, PdfFont regularFont) {
        // Table header
        float[] columnWidths = {5, 15, 15, 25, 15, 15, 10};
        Table table = new Table(UnitValue.createPercentArray(columnWidths));
        table.setWidth(UnitValue.createPercentValue(100));

        // Header row
        String[] headers = {"#", "First Name", "Last Name", "Email", "CIN", "Birthdate", "Role"};
        for (String header : headers) {
            Cell cell = new Cell();
            cell.setBackgroundColor(HEADER_BG_COLOR);
            cell.setBorder(new SolidBorder(HEADER_BG_COLOR, 1));
            cell.setPadding(12);

            Paragraph para = new Paragraph(header)
                    .setFont(boldFont)
                    .setFontColor(ColorConstants.WHITE)
                    .setFontSize(12)
                    .setBold()
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMargin(0);
            cell.add(para);
            table.addCell(cell);
        }

        // Data rows
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        boolean alternate = false;

        for (int i = 0; i < users.size(); i++) {
            User user = users.get(i);
            alternate = !alternate;

            // Row data
            addTableCell(table, String.valueOf(i + 1), regularFont, alternate, TextAlignment.CENTER);
            addTableCell(table, user.getFirstName() != null ? user.getFirstName() : "-", regularFont, alternate, TextAlignment.LEFT);
            addTableCell(table, user.getLastName() != null ? user.getLastName() : "-", regularFont, alternate, TextAlignment.LEFT);
            addTableCell(table, user.getEmail() != null ? user.getEmail() : "-", regularFont, alternate, TextAlignment.LEFT);
            addTableCell(table, user.getCinNumber() != null ? user.getCinNumber() : "-", regularFont, alternate, TextAlignment.CENTER);
            addTableCell(table, user.getBirthdate() != null ? dateFormat.format(user.getBirthdate()) : "-", regularFont, alternate, TextAlignment.CENTER);
            addTableCell(table, user.getRole() != null ? user.getRole() : "USER", regularFont, alternate, TextAlignment.CENTER);
        }

        document.add(table);
    }

    private void addTableCell(Table table, String text, PdfFont font, boolean alternate, TextAlignment alignment) {
        Cell cell = new Cell();
        if (alternate) {
            cell.setBackgroundColor(ROW_ALT_COLOR);
        }
        cell.setBorder(new SolidBorder(new DeviceRgb(222, 226, 230), 0.5f));
        cell.setPadding(8);

        Paragraph para = new Paragraph(text)
                .setFont(font)
                .setFontColor(TEXT_COLOR)
                .setFontSize(10)
                .setTextAlignment(alignment)
                .setMargin(0);
        cell.add(para);
        table.addCell(cell);
    }

    private void addFooter(Document document, PdfFont font) {
        document.add(new Paragraph().setMarginTop(30));

        // Decorative line
        document.add(new Paragraph("_______________________________" +
                "______________________________________________________________")
                .setFontColor(new DeviceRgb(222, 226, 230))
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(10));

        // Footer text
        Paragraph footer = new Paragraph()
                .setFont(font)
                .setFontSize(9)
                .setFontColor(LIGHT_GRAY)
                .setTextAlignment(TextAlignment.CENTER);

        footer.add("This report was generated by Finovate - Financial Management System\n");
        footer.add("© " + new SimpleDateFormat("yyyy").format(new Date()) + " Finovate. All rights reserved.");

        document.add(footer);
    }
}
